name: Deploy
run-name: ${{ github.actor }} is deploying frontend 🚀
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: 'main'

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: "22"
          cache: "npm"

      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          role-to-assume: ${{ vars.OIDC_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Upload to S3
        run: aws s3 sync dist/ s3://jovanovski.dev --delete

      - name: Invalidate CloudFront
        if: vars.CLOUDFRONT_DIST_ID != ''
        run: aws cloudfront create-invalidation --distribution-id ${{ vars.CLOUDFRONT_DIST_ID }} --paths "/*"
